# Generated by Django 4.0.5 on 2022-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('userphone', models.CharField(max_length=20)),
                ('recipe_title', models.CharField(max_length=100)),
                ('recipe', models.CharField(max_length=1000)),
                ('timedate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
