# Generated by Django 4.0.5 on 2022-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrecipes',
            name='recipe',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='allrecipes',
            name='userphone',
            field=models.CharField(max_length=10),
        ),
    ]
